---
# tasks file for vim

- name: install vim (Ubuntu)
  apt:
    name: vim
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install vim (CentOS)
  apt:
    name: vim
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"
